"""add_src_columns

Revision ID: 419fe6b1441c
Revises: af6c051ca400
Create Date: 2026-08-24 20:47:54.390512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '419fe6b1441c'
down_revision: Union[str, None] = 'af6c051ca400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Words', sa.Column('ease_factor', sa.Float(), nullable=True))
    op.add_column('Words', sa.Column('next_review', sa.DateTime(), nullable=True))
    op.drop_column('Words', 'interval')
    op.drop_column('Words', 'review_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Words', sa.Column('review_count', sa.INTEGER(), nullable=True))
    op.add_column('Words', sa.Column('interval', sa.INTEGER(), nullable=True))
    op.drop_column('Words', 'next_review')
    op.drop_column('Words', 'ease_factor')
    # ### end Alembic commands ###
